name: ASM_amd64_linux 1


on:
  push:
    paths:
      - '.github/workflows/asm_amd64_linux-1.yml'
      - 'asm_amd64_linux/hello_world_1/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install lld and nasm
        run: sudo apt install lld nasm
        
      - name: Build
        run: |
          cd asm_amd64_linux/hello_world_1
          make

      - name: Hello World!
        run: |
          cd asm_amd64_linux/hello_world_1
          ./helloasm
