name: Docker 1

on:
  push:
    paths:
      - '.github/workflows/docker-1.yml'
      - 'docker/main.sh'
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    container:
      image: docker
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello World!!
        run: ./docker/main.sh
