name: Elixir 1

on:
  push:
    paths:
      - '.github/workflows/elixir-1.yml'
      - 'elixir_lang/hello_world_1/**'
  workflow_dispatch:

jobs:
  build:
    name: Elixir 1
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.9.4'
          
      - name: Hello World!!
        run: |
          cd ./elixir_lang/hello_world_1/
          mix test
