name: JavaScript 1

on:
  push:
    paths:
      - '.github/worlflows/js-1.yml'
      - 'javascript/hello_world_1/**'
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: Hello World!!
        run: deno run ./javascript/hello_world_1/main.js
