name: Nadeshiko3-1

on:
  push:
    paths:
    - '.github/workflows/nadeshiko3-1.yml'
    - 'nadeshiko3/hello_world_1/**'
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install nadeshiko3
        run: npm install -g nadesiko3
        
      - name: Hello World!
        run: cnako3 ./nadeshiko3/hello_world_1/main.nako3
