name: Nim 1

on:
  push:
    paths:
      - ".github/workflows/nim-1.yaml"
      - "nim/hello_world_1/**"
  workflow_dispatch:

jobs:
  build:
    name: Nim 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1

      - name: Test "Hello World"
        run: |
          cd ./nim/hello_world_1/
          testament p 'tests/*.nim'

      - name: Compile Hello World
        run: |
          cd ./nim/hello_world_1/
          nim c -d:release src/main.nim
      - name: Run Hello World
        run: |
          cd ./nim/hello_world_1/
          ./src/main
