name: Rust 3

on:
  push:
    paths:
      - '.github/workflows/rust-3.yml'
      - 'rust/hello_world_3/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Rust 3
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup latest Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: |
          cd ./rust/hello_world_3/
          cargo build

      - name: Hello World!!
        run: ./rust/hello_world_3/target/debug/hello_world_3
