name: TypeScript 1

on:
  push:
    paths:
      - '.github/worlflows/ts-1.yml'
      - 'typescript/hello_world_1/**'
  pull_request:
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: Hello World!!
        run: deno run ./typescript/hello_world_1/index.ts
